rvm:
  - 1.8.7
  - 1.9.3
  - jruby-18mode
  - jruby-19mode
  - rbx-18mode
  - rbx-19mode
branches:
  only:
    - master
script: "bundle exec rake spec"
matrix:
  allow_failures:
    # The weekly rbx seems to have a bug that's fixed in HEAD
    - rvm: rbx-18mode
