language: ruby
gemfile:
  - Gemfile
  - Gemfile.1.8.7
rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - 2.0.0
  - jruby-18mode
  - jruby-19mode
  - rbx-18mode
  - rbx-19mode

matrix:
  include:
    - rvm: 1.8.7
      gemfile: Gemfile.1.8.7
    - rvm: 1.9.2
      gemfile: Gemfile
    - rvm: 1.9.3
      gemfile: Gemfile
    - rvm: 2.0.0
      gemfile: Gemfile
    - rvm: jruby-18mode
      gemfile: Gemfile.1.8.7
    - rvm: jruby-19mode
      gemfile: Gemfile
    - rvm: rbx-18mode
      gemfile: Gemfile.1.8.7
    - rvm: rbx-19mode
      gemfile: Gemfile

branches:
  only:
    - master

script: "bundle exec rake spec"

